name: Development test workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "develop" branch
  push:
    branches: [develop]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'develop'
  cancel-in-progress: false

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'
          cache: 'yarn'

      - name: Run tests
        env:
          PUBLIC_APP_NAME: ${{ vars.PUBLIC_APP_NAME }}
          PUBLIC_APP_DOMAIN: ${{ vars.PUBLIC_APP_DOMAIN }}
          PUBLIC_APP_URL: ${{ vars.PUBLIC_APP_URL }}
          PUBLIC_LINK_URI: ${{ vars.PUBLIC_LINK_URI }}
          PUBLIC_TOKEN_URI: ${{ vars.PUBLIC_TOKEN_URI }}
          PRIVATE_ENCRYPT_KEY: ${{ secrets.PRIVATE_ENCRYPT_KEY }}
          PRIVATE_ENCRYPT_SALT: ${{ secrets.PRIVATE_ENCRYPT_SALT }}
          PRIVATE_TOKEN_SECRET: ${{ secrets.PRIVATE_TOKEN_SECRET }}
          PRIVATE_TOKEN_EMAIL: ${{ secrets.PRIVATE_TOKEN_EMAIL }}

        run: |
          yarn
          yarn playwright install
          yarn test
