name: Development test workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "develop" branch
  push:
    branches: [develop]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'develop'
  cancel-in-progress: false

jobs:
  tests:
    uses: './.github/workflows/playwright.yaml'
    outputs:
      status: ${{ job.status }}
    secrets: inherit

  email:
    needs: tests
    uses: './.github/workflows/email.yaml'
    with:
      name: 'Tests'
      status: ${{ needs.tests.outputs.status }}
    secrets: inherit
